// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: govent.proto

package gapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Payload       string                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_govent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Event) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Event) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type QueueMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubscriberName string                 `protobuf:"bytes,2,opt,name=subscriber_name,json=subscriberName,proto3" json:"subscriber_name,omitempty"`
	EventId        string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Payload        string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueueMessage) Reset() {
	*x = QueueMessage{}
	mi := &file_govent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessage) ProtoMessage() {}

func (x *QueueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessage.ProtoReflect.Descriptor instead.
func (*QueueMessage) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{1}
}

func (x *QueueMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueueMessage) GetSubscriberName() string {
	if x != nil {
		return x.SubscriberName
	}
	return ""
}

func (x *QueueMessage) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *QueueMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueueMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_govent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateEventRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateEventRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_govent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEventResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateEventResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateEventResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateEventResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_govent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_govent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetEventResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetEventResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetEventResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_govent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       string                 `protobuf:"bytes,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_govent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEventResponse) GetDeleted() string {
	if x != nil {
		return x.Deleted
	}
	return ""
}

type AllEventsBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllEventsBySlugRequest) Reset() {
	*x = AllEventsBySlugRequest{}
	mi := &file_govent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllEventsBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllEventsBySlugRequest) ProtoMessage() {}

func (x *AllEventsBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllEventsBySlugRequest.ProtoReflect.Descriptor instead.
func (*AllEventsBySlugRequest) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{8}
}

func (x *AllEventsBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type AllEventsBySlugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllEventsBySlugResponse) Reset() {
	*x = AllEventsBySlugResponse{}
	mi := &file_govent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllEventsBySlugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllEventsBySlugResponse) ProtoMessage() {}

func (x *AllEventsBySlugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllEventsBySlugResponse.ProtoReflect.Descriptor instead.
func (*AllEventsBySlugResponse) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{9}
}

func (x *AllEventsBySlugResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type AllEventsBySlugAndSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllEventsBySlugAndSourceRequest) Reset() {
	*x = AllEventsBySlugAndSourceRequest{}
	mi := &file_govent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllEventsBySlugAndSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllEventsBySlugAndSourceRequest) ProtoMessage() {}

func (x *AllEventsBySlugAndSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllEventsBySlugAndSourceRequest.ProtoReflect.Descriptor instead.
func (*AllEventsBySlugAndSourceRequest) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{10}
}

func (x *AllEventsBySlugAndSourceRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *AllEventsBySlugAndSourceRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type AllEventsBySlugAndSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllEventsBySlugAndSourceResponse) Reset() {
	*x = AllEventsBySlugAndSourceResponse{}
	mi := &file_govent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllEventsBySlugAndSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllEventsBySlugAndSourceResponse) ProtoMessage() {}

func (x *AllEventsBySlugAndSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllEventsBySlugAndSourceResponse.ProtoReflect.Descriptor instead.
func (*AllEventsBySlugAndSourceResponse) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{11}
}

func (x *AllEventsBySlugAndSourceResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type CreateSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriberName string                 `protobuf:"bytes,1,opt,name=subscriber_name,json=subscriberName,proto3" json:"subscriber_name,omitempty"`
	EventName      string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Source         string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_govent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSubscriptionRequest) GetSubscriberName() string {
	if x != nil {
		return x.SubscriberName
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CreateSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_govent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSubscriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PullMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessagesRequest) Reset() {
	*x = PullMessagesRequest{}
	mi := &file_govent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesRequest) ProtoMessage() {}

func (x *PullMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesRequest.ProtoReflect.Descriptor instead.
func (*PullMessagesRequest) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{14}
}

func (x *PullMessagesRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *PullMessagesRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type PullMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*QueueMessage        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessagesResponse) Reset() {
	*x = PullMessagesResponse{}
	mi := &file_govent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesResponse) ProtoMessage() {}

func (x *PullMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesResponse.ProtoReflect.Descriptor instead.
func (*PullMessagesResponse) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{15}
}

func (x *PullMessagesResponse) GetMessages() []*QueueMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AckMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessageRequest) Reset() {
	*x = AckMessageRequest{}
	mi := &file_govent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageRequest) ProtoMessage() {}

func (x *AckMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageRequest.ProtoReflect.Descriptor instead.
func (*AckMessageRequest) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{16}
}

func (x *AckMessageRequest) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

type AckMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessageResponse) Reset() {
	*x = AckMessageResponse{}
	mi := &file_govent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageResponse) ProtoMessage() {}

func (x *AckMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_govent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageResponse.ProtoReflect.Descriptor instead.
func (*AckMessageResponse) Descriptor() ([]byte, []int) {
	return file_govent_proto_rawDescGZIP(), []int{17}
}

func (x *AckMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_govent_proto protoreflect.FileDescriptor

const file_govent_proto_rawDesc = "" +
	"\n" +
	"\fgovent.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x06 \x01(\tR\apayload\"\x94\x01\n" +
	"\fQueueMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fsubscriber_name\x18\x02 \x01(\tR\x0esubscriberName\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\"Z\n" +
	"\x12CreateEventRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\"k\n" +
	"\x13CreateEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\"!\n" +
	"\x0fGetEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"h\n" +
	"\x10GetEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteEventResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\tR\adeleted\",\n" +
	"\x16AllEventsBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"?\n" +
	"\x17AllEventsBySlugResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\"M\n" +
	"\x1fAllEventsBySlugAndSourceRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"H\n" +
	" AllEventsBySlugAndSourceResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\"{\n" +
	"\x19CreateSubscriptionRequest\x12'\n" +
	"\x0fsubscriber_name\x18\x01 \x01(\tR\x0esubscriberName\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"P\n" +
	"\x1aCreateSubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x13PullMessagesRequest\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"G\n" +
	"\x14PullMessagesResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.event.QueueMessageR\bmessages\".\n" +
	"\x11AckMessageRequest\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\".\n" +
	"\x12AckMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa5\x04\n" +
	"\fEventservice\x12D\n" +
	"\vCreateEvent\x12\x19.event.CreateEventRequest\x1a\x1a.event.CreateEventResponse\x12;\n" +
	"\bGetEvent\x12\x16.event.GetEventRequest\x1a\x17.event.GetEventResponse\x12D\n" +
	"\vDeleteEvent\x12\x19.event.DeleteEventRequest\x1a\x1a.event.DeleteEventResponse\x12e\n" +
	"\x12AllBySlugAndSource\x12&.event.AllEventsBySlugAndSourceRequest\x1a'.event.AllEventsBySlugAndSourceResponse\x12Y\n" +
	"\x12CreateSubscription\x12 .event.CreateSubscriptionRequest\x1a!.event.CreateSubscriptionResponse\x12G\n" +
	"\fPullMessages\x12\x1a.event.PullMessagesRequest\x1a\x1b.event.PullMessagesResponse\x12A\n" +
	"\n" +
	"AckMessage\x12\x18.event.AckMessageRequest\x1a\x19.event.AckMessageResponseB!Z\x1fmarkitos-it-svc-event-grpc/gapib\x06proto3"

var (
	file_govent_proto_rawDescOnce sync.Once
	file_govent_proto_rawDescData []byte
)

func file_govent_proto_rawDescGZIP() []byte {
	file_govent_proto_rawDescOnce.Do(func() {
		file_govent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_govent_proto_rawDesc), len(file_govent_proto_rawDesc)))
	})
	return file_govent_proto_rawDescData
}

var file_govent_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_govent_proto_goTypes = []any{
	(*Event)(nil),                            // 0: event.Event
	(*QueueMessage)(nil),                     // 1: event.QueueMessage
	(*CreateEventRequest)(nil),               // 2: event.CreateEventRequest
	(*CreateEventResponse)(nil),              // 3: event.CreateEventResponse
	(*GetEventRequest)(nil),                  // 4: event.GetEventRequest
	(*GetEventResponse)(nil),                 // 5: event.GetEventResponse
	(*DeleteEventRequest)(nil),               // 6: event.DeleteEventRequest
	(*DeleteEventResponse)(nil),              // 7: event.DeleteEventResponse
	(*AllEventsBySlugRequest)(nil),           // 8: event.AllEventsBySlugRequest
	(*AllEventsBySlugResponse)(nil),          // 9: event.AllEventsBySlugResponse
	(*AllEventsBySlugAndSourceRequest)(nil),  // 10: event.AllEventsBySlugAndSourceRequest
	(*AllEventsBySlugAndSourceResponse)(nil), // 11: event.AllEventsBySlugAndSourceResponse
	(*CreateSubscriptionRequest)(nil),        // 12: event.CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil),       // 13: event.CreateSubscriptionResponse
	(*PullMessagesRequest)(nil),              // 14: event.PullMessagesRequest
	(*PullMessagesResponse)(nil),             // 15: event.PullMessagesResponse
	(*AckMessageRequest)(nil),                // 16: event.AckMessageRequest
	(*AckMessageResponse)(nil),               // 17: event.AckMessageResponse
	(*timestamppb.Timestamp)(nil),            // 18: google.protobuf.Timestamp
}
var file_govent_proto_depIdxs = []int32{
	18, // 0: event.Event.created_at:type_name -> google.protobuf.Timestamp
	18, // 1: event.Event.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: event.AllEventsBySlugResponse.events:type_name -> event.Event
	0,  // 3: event.AllEventsBySlugAndSourceResponse.events:type_name -> event.Event
	1,  // 4: event.PullMessagesResponse.messages:type_name -> event.QueueMessage
	2,  // 5: event.Eventservice.CreateEvent:input_type -> event.CreateEventRequest
	4,  // 6: event.Eventservice.GetEvent:input_type -> event.GetEventRequest
	6,  // 7: event.Eventservice.DeleteEvent:input_type -> event.DeleteEventRequest
	10, // 8: event.Eventservice.AllBySlugAndSource:input_type -> event.AllEventsBySlugAndSourceRequest
	12, // 9: event.Eventservice.CreateSubscription:input_type -> event.CreateSubscriptionRequest
	14, // 10: event.Eventservice.PullMessages:input_type -> event.PullMessagesRequest
	16, // 11: event.Eventservice.AckMessage:input_type -> event.AckMessageRequest
	3,  // 12: event.Eventservice.CreateEvent:output_type -> event.CreateEventResponse
	5,  // 13: event.Eventservice.GetEvent:output_type -> event.GetEventResponse
	7,  // 14: event.Eventservice.DeleteEvent:output_type -> event.DeleteEventResponse
	11, // 15: event.Eventservice.AllBySlugAndSource:output_type -> event.AllEventsBySlugAndSourceResponse
	13, // 16: event.Eventservice.CreateSubscription:output_type -> event.CreateSubscriptionResponse
	15, // 17: event.Eventservice.PullMessages:output_type -> event.PullMessagesResponse
	17, // 18: event.Eventservice.AckMessage:output_type -> event.AckMessageResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_govent_proto_init() }
func file_govent_proto_init() {
	if File_govent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_govent_proto_rawDesc), len(file_govent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_govent_proto_goTypes,
		DependencyIndexes: file_govent_proto_depIdxs,
		MessageInfos:      file_govent_proto_msgTypes,
	}.Build()
	File_govent_proto = out.File
	file_govent_proto_goTypes = nil
	file_govent_proto_depIdxs = nil
}
